#!/usr/bin/env bash
# query.sh [--deep] <query...>
# Searches cold skills by regenerating an index and matching the query.
# Flow: update index -> query index -> fallback to hot skills -> suggest --deep.
set -euo pipefail

COLD_DIR="${COLD_SKILLS_DIR:-$HOME/.agents/skills-cold}"
HOT_DIR="${HOT_SKILLS_DIR:-$HOME/.agents/skills}"
INDEX="$COLD_DIR/INDEX.md"

DEEP=0
if [ "${1:-}" = "--deep" ]; then DEEP=1; shift; fi
QUERY="${*:-}"
if [ -z "$QUERY" ]; then
  echo "usage: query.sh [--deep] <query>" >&2
  exit 2
fi

# 1. Regenerate index: one line per skill -> "name | description"
{
  echo "# Cold Skills Index (auto-generated by search-cold-skills/scripts/query.sh)"
  find "$COLD_DIR" -maxdepth 3 -name SKILL.md | sort | while read -r f; do
    rel=$(dirname "${f#"$COLD_DIR"/}")
    name=$(sed -n 's/^name:[[:space:]]*//p' "$f" | head -1)
    [ -n "$name" ] || name=$(basename "$rel")
    desc=$(sed -n 's/^description:[[:space:]]*//p' "$f" | head -1 | tr -d '"')
    echo "$name | $rel | $desc"
  done
} > "$INDEX"

# Build fuzzy pattern: raw query, hyphenated, plus each word (with common stems trimmed)
pattern="$QUERY"
hyphenated="${QUERY// /-}"
[ "$hyphenated" != "$QUERY" ] && pattern="$pattern|$hyphenated"
for w in $QUERY; do
  stem=$(echo "$w" | sed -E 's/(ist|ing|ed|es|s)$//')
  [ ${#stem} -ge 3 ] && pattern="$pattern|$stem"
done

# 2. Query the index
matches=$(rg -i "$pattern" "$INDEX" | rg -v '^#' || true)
if [ -n "$matches" ]; then
  echo "cold skill matches:"
  echo "$matches" | while IFS='|' read -r name rel _; do
    name=$(echo "$name" | xargs); rel=$(echo "$rel" | xargs)
    echo "  $name -> $COLD_DIR/$rel/SKILL.md"
  done
  exit 0
fi

# 3. Deep search of full cold skill bodies (takes priority over hot fallback)
if [ "$DEEP" = 1 ]; then
  deep=$(rg -il --glob 'SKILL.md' "$pattern" "$COLD_DIR" || true)
  if [ -n "$deep" ]; then
    echo "deep cold matches (found in skill bodies, not index):"
    echo "$deep" | sed 's/^/  /'
    exit 0
  fi
fi

# 4. Fallback: check hot skills (frontmatter only)
hot=$(rg -il --glob 'SKILL.md' "$pattern" "$HOT_DIR" 2>/dev/null || true)
if [ -n "$hot" ]; then
  echo "no cold skill match. hot skill matches (tell the user you fell back to a hot skill):"
  echo "$hot" | sed 's/^/  /'
  exit 0
fi

if [ "$DEEP" = 1 ]; then
  echo "no matches anywhere for: $QUERY"
  exit 1
fi

echo "no matches in cold index or hot skills for: $QUERY"
echo "try: query.sh --deep $QUERY  (searches full SKILL.md bodies, not just index)"
exit 1
