# query.ps1 [-Deep] <query...>
# Searches cold skills by regenerating an index and matching the query.
# Flow: update index -> query index -> fallback to hot skills -> suggest -Deep.
# -Deep (switch) and --deep (first arg) both enable full-body search.
param([Alias('Deep')][switch]$DeepSearch)

$ColdDir = $env:COLD_SKILLS_DIR ?? (Join-Path $HOME '.agents\skills-cold')
$HotDir  = $env:HOT_SKILLS_DIR  ?? (Join-Path $HOME '.agents\skills')
$Index   = Join-Path $ColdDir 'INDEX.md'

# Accept "query.ps1 --deep <query>" (query.sh parity) in addition to -Deep.
$tokens = @($args)
if ($tokens.Count -gt 0 -and $tokens[0] -eq '--deep') {
  $DeepSearch = $true
  $tokens = @($tokens | Select-Object -Skip 1)
}
$Query = $tokens -join ' '
if (-not $Query) {
  Write-Error 'usage: query.ps1 [-Deep] <query>'
  exit 2
}

# 1. Regenerate index: one line per skill -> "name | relative-dir | description"
if (Test-Path -LiteralPath $ColdDir) {
  $indexLines = [System.Collections.Generic.List[string]]::new()
  $indexLines.Add('# Cold Skills Index (auto-generated by search-cold-skills/scripts/query.ps1)')
  # Canonical long form so the substring below matches Get-ChildItem FullName
  # (Resolve-Path keeps 8.3 short names; Get-ChildItem expands them).
  $coldRoot = (Get-Item -LiteralPath $ColdDir).FullName.TrimEnd('\', '/')
  foreach ($f in Get-ChildItem -LiteralPath $coldRoot -Recurse -Depth 2 -Filter 'SKILL.md' -File | Sort-Object FullName) {
    $rel = Split-Path -Parent $f.FullName
    $rel = $rel.Substring($coldRoot.Length).TrimStart('\', '/')
    $body = Get-Content -LiteralPath $f.FullName -Raw
    $name = [regex]::Match($body, '(?m)^name:[ \t]*(.*)$').Groups[1].Value.Trim()
    $leaf = Split-Path -Leaf $rel
    if (-not $name) { $name = if ($leaf) { $leaf } else { $f.Directory.Name } }
    $desc = [regex]::Match($body, '(?m)^description:[ \t]*(.*)$').Groups[1].Value.Trim() -replace '"', ''
    $indexLines.Add("$name | $rel | $desc")
  }
  Set-Content -LiteralPath $Index -Value $indexLines -Encoding utf8
}

# Build fuzzy pattern: raw query, hyphenated, plus each word (common stems trimmed)
$pattern = [regex]::Escape($Query)
$hyphenated = $Query -replace ' ', '-'
if ($hyphenated -ne $Query) { $pattern += '|' + [regex]::Escape($hyphenated) }
foreach ($w in $Query -split ' ') {
  if (-not $w) { continue }
  $stem = [regex]::Replace($w, '(ist|ing|ed|es|s)$', '')
  if ($stem.Length -ge 3) { $pattern += '|' + [regex]::Escape($stem) }
}

# 2. Query the index
$matches = @(
  if (Test-Path -LiteralPath $Index) {
    Select-String -LiteralPath $Index -Pattern $pattern | Where-Object { $_.Line -notmatch '^#' }
  }
)
if ($matches.Count -gt 0) {
  Write-Host 'cold skill matches:'
  foreach ($m in $matches) {
    $parts = $m.Line -split '\|', 3
    $name = $parts[0].Trim()
    $rel  = $parts[1].Trim()
    Write-Host "  $name -> $(Join-Path $ColdDir (Join-Path $rel 'SKILL.md'))"
  }
  exit 0
}

# 3. Deep search of full cold skill bodies (takes priority over hot fallback)
if ($DeepSearch -and (Test-Path -LiteralPath $ColdDir)) {
  $deep = @(
    Get-ChildItem -LiteralPath $ColdDir -Recurse -Depth 2 -Filter 'SKILL.md' -File |
      Where-Object { Select-String -LiteralPath $_.FullName -Pattern $pattern -Quiet } |
      ForEach-Object FullName
  )
  if ($deep.Count -gt 0) {
    Write-Host 'deep cold matches (found in skill bodies, not index):'
    $deep | ForEach-Object { Write-Host "  $_" }
    exit 0
  }
}

# 4. Fallback: check hot skills (full SKILL.md content)
$hot = @(
  Get-ChildItem -LiteralPath $HotDir -Recurse -Filter 'SKILL.md' -File -ErrorAction SilentlyContinue |
    Where-Object { Select-String -LiteralPath $_.FullName -Pattern $pattern -Quiet } |
    ForEach-Object FullName
)
if ($hot.Count -gt 0) {
  Write-Host 'no cold skill match. hot skill matches (tell the user you fell back to a hot skill):'
  $hot | ForEach-Object { Write-Host "  $_" }
  exit 0
}

if ($DeepSearch) {
  Write-Host "no matches anywhere for: $Query"
  exit 1
}

Write-Host "no matches in cold index or hot skills for: $Query"
Write-Host "try: query.ps1 -Deep $Query  (searches full SKILL.md bodies, not just index)"
exit 1
